import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Icon, AddButtonWithModal } from "./components";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Notes Synterra",
  description: "Generated by Roman Ohiienko with love and some coffee",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <aside className="p-4 rounded-lg w-fit bg-[#0e0c12]">
          <h1 className="font-extrabold flex gap-2 items-center text-[#af95d6]">
            <span className="text-white max-sm:hidden">Synterra</span>{" "}
            <span className="max-[480px]:hidden">Notes</span>
            <Icon.Logo />
          </h1>
        </aside>
        <main className="p-4 relative w-full h-full grid grid-cols-[repeat(auto-fill,_minmax(200px,_1fr))] gap-3 auto-rows-auto overflow-auto bg-[#0e0c12] rounded-lg">
          {children}
          <AddButtonWithModal />
        </main>
      </body>
    </html>
  );
}
